image_speed = 0.35;
scr_collision_init();
grav = 0.3;
state = states.normal;
substate = states.normal;
grabber = -4;
xscale_mult = 1;
yscale_mult = 1;
longRangeDistance = 400;
shortRangeDistance = 100;
attack_func = -4;
step_func = -4;
attack_cooldown = 0;
zombie_inst = -4;
grabbable = true;
